export const genreMap = [
  ["#ec66c6", "Pop", "Bubblegum pop", "black"],
  ["#a259ff", "Dance pop", "Synth pop", "white"],
  ["#5d62da", "Indie pop", "", "white"],
  ["#b17bb6", "Pop rock", "Soft rock", "white"],
  ["#da09c5", "Disco", "", "white"],
  ["#933f67", "Funk", "", "white"],
  ["#fe5c5c", "Pop rap", "", "white"],
  ["#cf0a45", "R&B", "", "white"],
  ["#a73138", "New jack", "Doo-wop", "white"],
  ["#860000", "Hip hop", "", "white"],
  ["#530a00", "Trap", "Dirty south, Crunk", "white"],
  ["#422727", "Regional hip hop", "East coast, West coast", "white"],
  ["#865b3c", "Alt hip hop", "Experimental rap", "white"],
  ["#0ba135", "Rock", "", "white"],
  ["#04612f", "Metal", "Hard rock, Heavy metal, Nu metal", "white"],
  ["#3f6539", "Grunge", "Nu grunge", "white"],
  ["#537e0b", "Funk rock", "Blues rock", "white"],
  ["#319c7a", "New Wave", "Punk", "white"],
  ["#21d811", "Rock and roll", "Rockabilly", "black"],
  ["#79c999", "Alternative", "", "black"],
  ["#8dea6c", "Folk rock", "", "black"],
  ["#baa912", "Soul", "", "black"],
  ["#8f845a", "Blues", "", "white"],
  ["#e8f92d", "Jazz", "Swing", "black"],
  ["#ddf3a8", "Soca", "Calypso", "black"],
  ["#be8f7a", "Gospel", "Worship", "black"],
  ["#bcbdb9", "World", "New age", "black"],
  ["#2d62eb", "EDM", "", "white"],
  ["#162be9", "Dubstep", "", "white"],
  ["#008ea1", "Electro rock", "", "white"],
  ["#7d2ffd", "Reggae", "Dancehall, Afrobeat", "white"],
  ["#1ce8e8", "Eurodance", "Trance", "black"],
  ["#009adc", "House", "", "white"],
  ["#e56000", "Country", "", "white"],
  ["#fe965c", "Country pop", "", "black"],
  ["#8f5a0a", "Country rock", "", "white"],
  ["#a31f0d", "Country Rap", "", "white"],
  ["#c7cc86", "Folk", "Bluegrass", "black"],
  ["#f8d763", "Latin", "", "black"],
  ["#ffd4d1", "Tango", "", "black"],
];
