export const genreMap = [
  ["#ec66c6", "Pop", "black"],
  ["#a259ff", "Dance pop", "white"],
  ["#5d62da", "Indie pop", "white"],
  ["#b17bb6", "Pop rock", "white"],
  ["#da09c5", "Disco", "white"],
  ["#933f67", "Funk", "white"],
  ["#fe5c5c", "Pop rap", "white"],
  ["#cf0a45", "R&B", "white"],
  ["#a73138", "New jack", "white"],
  ["#860000", "Hip hop", "white"],
  ["#530a00", "Trap", "white"],
  ["#422727", "Regional hip hop", "white"],
  ["#865b3c", "Alt hip hop", "white"],
  ["#0ba135", "Rock", "white"],
  ["#04612f", "Metal", "white"],
  ["#3f6539", "Grunge", "white"],
  ["#537e0b", "Funk rock", "white"],
  ["#319c7a", "New Wave", "white"],
  ["#21d811", "Rock and roll", "black"],
  ["#79c999", "Alternative", "black"],
  ["#8dea6c", "Folk rock", "black"],
  ["#baa912", "Soul", "black"],
  ["#8f845a", "Blues", "white"],
  ["#e8f92d", "Jazz", "black"],
  ["#ddf3a8", "Soca", "black"],
  ["#be8f7a", "Gospel", "black"],
  ["#bcbdb9", "World", "black"],
  ["#2d62eb", "EDM", "white"],
  ["#162be9", "Dubstep", "white"],
  ["#008ea1", "Electro rock", "white"],
  ["#7d2ffd", "Reggae/Dancehall", "white"],
  ["#1ce8e8", "Eurodance", "black"],
  ["#009adc", "House", "white"],
  ["#e56000", "Country", "white"],
  ["#fe965c", "Country pop", "black"],
  ["#8f5a0a", "Country rock", "white"],
  ["#a31f0d", "Country Rap", "white"],
  ["#c7cc86", "Folk", "black"],
  ["#f8d763", "Latin", "black"],
  ["#ffd4d1", "Tango", "black"],
];
